name: Hotspot Data Crawler

on:
  schedule:
    # 每15分钟运行一次（北京时间 0,15,30,45分）
    - cron: '*/15 * * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  crawl-hotspot-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run hotspot crawler
      run: python fix_crawler.py

    - name: Generate task report
      run: |
        echo "=== Hotspot Crawler Task Report ==="
        echo "Run Time: $(date '+%Y-%m-%d %H:%M:%S')"
        echo "Data Files:"
        ls -la hotspot_data_*.json
        echo "=== Report End ==="

    - name: Upload hotspot data
      uses: actions/upload-artifact@v3
      with:
        name: hotspot-data
        path: hotspot_data_*.json

    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add hotspot_data_*.json
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update hotspot data [$(date '+%Y-%m-%d %H:%M')]"
          git push
          echo "Changes committed and pushed"
        fi